### ISSUE TITLE
Supplemental API Routes Return 500 Error

### ISSUE THREAD

**Issue by ahmattox** [Seafood-Globalization-Lab/ARTIS-API#7]
Example Request:
```
GET /supplemental/query?table=countries&cols_wanted=iso3c,country_name,owid_region,continent&search_criteria=0 HTTP/1.1
X-API-KEY: XXX
Host: artis-a845c2b00aea.herokuapp.com
Connection: close
User-Agent: RapidAPI/4.2.0 (Macintosh; OS X/14.5.0) GCDHTTPRequest
```

Response:

```
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Report-To: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1719341484&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=P%2BMYQ9yJRTUaDVJfVbSPxoBdWiGt46%2Fz5HdZWFVpIMo%3D"}]}
Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1719341484&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=P%2BMYQ9yJRTUaDVJfVbSPxoBdWiGt46%2Fz5HdZWFVpIMo%3D
Nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
Connection: close
X-Powered-By: Express
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Etag: W/"15-/6VXivhc2MKdLfIkLcUE47K6aH0"
Date: Tue, 25 Jun 2024 18:51:24 GMT
Via: 1.1 vegur

Internal Server Error
```

Server Logs:
```
2024-06-25T18:57:12.882417+00:00 heroku[router]: at=info method=GET path="/supplemental/query?table=countries&cols_wanted=iso3c,country_name,owid_region,continent&search_criteria=0" host=artis-a845c2b00aea.herokuapp.com request_id=fc0fcce3-4f1f-43ef-a4e8-454a8418b657 fwd="73.173.92.17" dyno=web.1 connect=0ms service=24ms status=500 bytes=241 protocol=https
2024-06-25T18:57:12.881634+00:00 app[web.1]: Error: Error: error: relation "countries" does not exist
2024-06-25T18:57:12.881682+00:00 app[web.1]: at /app/dist/db/supplemental.js:72:15
2024-06-25T18:57:12.881683+00:00 app[web.1]: at Generator.throw (<anonymous>)
2024-06-25T18:57:12.881683+00:00 app[web.1]: at rejected (/app/dist/db/supplemental.js:6:65)
2024-06-25T18:57:12.881683+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-06-25T18:57:12.000000+00:00 app[postgres.2529205]: [GOLD] [21-1]  sql_error_code = 42P01 time_ms = "2024-06-25 18:57:12.881 UTC" pid="1435122" proc_start_time="2024-06-25 18:57:12 UTC" session_id="667b1308.15e5f2" vtid="4/3758322" tid="0" log_line="4" database="dekn24t9v2f154" connection_source="3.235.175.86(41574)" user="uedg5kjabjsbg0" application_name="[unknown]" ERROR:  relation "countries" does not exist at character 57
2024-06-25T18:57:12.000000+00:00 app[postgres.2529205]: [GOLD] [21-2]  sql_error_code = 42P01 time_ms = "2024-06-25 18:57:12.881 UTC" pid="1435122" proc_start_time="2024-06-25 18:57:12 UTC" session_id="667b1308.15e5f2" vtid="4/3758322" tid="0" log_line="5" database="dekn24t9v2f154" connection_source="3.235.175.86(41574)" user="uedg5kjabjsbg0" application_name="[unknown]" STATEMENT:  SELECT iso3c, country_name, owid_region, continent FROM countries
```

Additional URLs returning similar 500 errors

- `https://artis-a845c2b00aea.herokuapp.com/supplemental?table=countries&variable=iso3c`
- `https://artis-a845c2b00aea.herokuapp.com/supplemental?table=sciname&variable=sciname`
- `https://artis-a845c2b00aea.herokuapp.com/supplemental/query?table=sciname&cols_wanted=sciname,common_name,genus,subfamily,family,order,class,superclass,phylum,kingdom,isscaap&search_criteria=1&genus=thunnus`

**Comment by rahulAgrBej** [comment]
Resolved, all URLs mentioned no longer return an error and return appropriate results with the most up to date data.
